# >>> Generated by pywal (do not edit) >>>
client.focused          {color4} {color4} {color15} {color4}
client.focused_inactive {color0} {color0} {color7}  {color0}
client.unfocused        {color0} {color0} {color7}  {color0}
client.urgent           {color1} {color1} {color15} {color1}
# <<< End pywal generated <<<
